import type { ITheme } from "@xterm/xterm";
export const terminalFontFamily = '"Cascadia Mono", "Cascadia Code", Consolas, Menlo, "DejaVu Sans Mono", monospace';
export const terminalThemes: Record<string, { label: string; theme: ITheme }> =
  {
    graphite: {
      label: "Graphite · vivid",
      theme: {
        background: "#0d1117",
        foreground: "#e6edf3",
        cursor: "#58a6ff",
        cursorAccent: "#0d1117",
        selectionBackground: "#264f78",
        selectionInactiveBackground: "#263548",
        black: "#30363d",
        red: "#ff6b6b",
        green: "#3fb950",
        yellow: "#e3b341",
        blue: "#58a6ff",
        magenta: "#d58cff",
        cyan: "#39c5cf",
        white: "#d0d7de",
        brightBlack: "#8b949e",
        brightRed: "#ff9492",
        brightGreen: "#56e36f",
        brightYellow: "#ffd866",
        brightBlue: "#79c0ff",
        brightMagenta: "#e2b0ff",
        brightCyan: "#56e8ed",
        brightWhite: "#ffffff",
      },
    },
    midnight: {
      label: "Midnight · blue",
      theme: {
        background: "#101b2b",
        foreground: "#d5e3f0",
        cursor: "#78c7ff",
        selectionBackground: "#30516eaa",
        black: "#233248",
        red: "#f08292",
        green: "#80d4a8",
        yellow: "#e9cc83",
        blue: "#7eaefa",
        magenta: "#b6a0ed",
        cyan: "#74d4e0",
        white: "#cfdaea",
        brightBlack: "#697e9c",
        brightRed: "#ffadb8",
        brightGreen: "#a7edc4",
        brightYellow: "#ffe4a7",
        brightBlue: "#a2ccff",
        brightMagenta: "#d6c3ff",
        brightCyan: "#acf2f5",
        brightWhite: "#f2f7ff",
      },
    },
    forest: {
      label: "Forest · green",
      theme: {
        background: "#10201c",
        foreground: "#d1e4d7",
        cursor: "#9ee5b4",
        selectionBackground: "#3b604b99",
        black: "#24392d",
        red: "#eb9b91",
        green: "#8ed1a0",
        yellow: "#d9cf91",
        blue: "#93bcd1",
        magenta: "#c1a8c9",
        cyan: "#83cbb6",
        white: "#d1ded3",
        brightBlack: "#74917e",
        brightRed: "#ffc0b1",
        brightGreen: "#b4efbf",
        brightYellow: "#f3e6b1",
        brightBlue: "#b6dcec",
        brightMagenta: "#dec6e6",
        brightCyan: "#b2ebda",
        brightWhite: "#ecf5ee",
      },
    },
    ember: {
      label: "Ember · warm",
      theme: {
        background: "#241a18",
        foreground: "#eadbd0",
        cursor: "#efbd83",
        selectionBackground: "#78513c88",
        black: "#3d2e28",
        red: "#e68d7d",
        green: "#b5c991",
        yellow: "#ebc180",
        blue: "#a5b9d0",
        magenta: "#d0a0bd",
        cyan: "#95c4bf",
        white: "#e0d4ca",
        brightBlack: "#9a8475",
        brightRed: "#ffb5a2",
        brightGreen: "#d2e2b1",
        brightYellow: "#ffe0a7",
        brightBlue: "#c5d8eb",
        brightMagenta: "#edc2dc",
        brightCyan: "#b8e2dc",
        brightWhite: "#fff3e9",
      },
    },
    paper: {
      label: "Paper · light",
      theme: {
        background: "#f1eee6",
        foreground: "#303b43",
        cursor: "#276859",
        selectionBackground: "#92b7c177",
        black: "#303b43",
        red: "#a63d46",
        green: "#31704f",
        yellow: "#976c22",
        blue: "#3a63a0",
        magenta: "#87549a",
        cyan: "#28787f",
        white: "#d0cec5",
        brightBlack: "#6c7474",
        brightRed: "#c65158",
        brightGreen: "#448060",
        brightYellow: "#a87c32",
        brightBlue: "#5079b4",
        brightMagenta: "#9e69ad",
        brightCyan: "#448b90",
        brightWhite: "#fffdf7",
      },
    },
  };
export function terminalTheme(id: string) {
  return terminalThemes[id]?.theme ?? terminalThemes.graphite.theme;
}
